-
    title: Design 
    uri: design/colors.html
    items:
        -
            title: Colors
            uri: design/colors.html
        -
            title: Layout
            uri: design/layout.html
        -
            title: Typography
            uri: design/typography.html
        -
            title: Graphics
            uri: design/graphics.html
        -
            title: Icons
            uri: design/icons.html

-
    title: Components
    uri: components/icons.html
    items:
        -
            title: Icons
            uri: components/icons.html
        -
            title: Graphics
            uri: components/graphics.html
        -
            title: Buttons
            uri: components/buttons.html
        -
            title: Forms
            uri: components/forms.html
        -
            title: Navigation
            uri: components/navigation.html
        -
            title: Tables
            uri: components/tables.html
-
    title: Source files
    uri: source-files/design.html
    items:
        -
            title: Design
            uri: source-files/design.html
