# PDS demo/config/config.yml
# General config file for the demo site
version : 1.0
styleguide:
    title : ProDemos Design System
    brand: ProDemos
    outputs: 
        - example
        # - twig
        - html
colors:
    # should be defined in assets/sass/variables/overrides
    white:
    black:
        - black-120
        - black-110
        - black-80
        - black-60
        - black-40
        - black-20
    creme:
        - creme-120
        - creme-110
        - creme-80 
        - creme-60 
        - creme-40 
        - creme-20
    yellow:
        - yellow-120  
        - yellow-110      
        - yellow-80
        - yellow-60
        - yellow-40
        - yellow-20
    orange:
        - orange-120
        - orange-110
        - orange-80 
        - orange-60 
        - orange-40 
        - orange-20 
    red:
        - red-120
        - red-110
        - red-80
        - red-60
        - red-40
        - red-20
    pink:
        - pink-120
        - pink-110
        - pink-80
        - pink-60
        - pink-40
        - pink-20
    purple:
        - purple-120
        - purple-110
        - purple-80
        - purple-60
        - purple-40
        - purple-20
    blue:
        - blue-120
        - blue-110
        - blue-80 
        - blue-60 
        - blue-40 
        - blue-20   
    green:
        - green-120
        - green-110
        - green-80
        - green-60
        - green-40
        - green-20

themes:
        creme01 : Creme 01
        yellow01 : Yellow 01 
        orange01 : Orange 01
        red01 : Red 01
        pink01 : Pink 01 
        purple01 : Purple 01 
        blue01 : Blue 01
        green01 : Green 01

components:
    # will be read from the demo/config/components/ directory
    # by the compile script

images:
    # will be read from the assets/images/ directory
    # by the compile script
    
icons:
    # will be read from the assets/images/icons directory
    # by the compile script

