-
    title: Design 
    uri: design/colors.html
    items:
        -
            title: Colors
            uri: design/colors.html
        -
            title: Layout
            uri: design/layout.html
        -
            title: Typography
            uri: design/typography.html
        -
            title: Graphics
            uri: design/graphics.html
        -
            title: Icons
            uri: design/icons.html

-
    title: Components
    uri: components/icons.html
    items:
        -
            title: Icons
            uri: components/icons.html
        -
            title: Logos
            uri: components/logos.html
        -
            title: Buttons
            uri: components/buttons.html
        -
            title: Forms
            uri: components/forms.html
        -
            title: Navigation
            uri: components/navigation.html
        -
            title: Tables
            uri: components/tables.html
-
    title: Helpers
    uri: helpers/colors.html
    items:
        -
            title: Colors
            uri: helpers/colors.html
        -
            title: Typography
            uri: helpers/typography.html
        -
            title: Responsive
            uri: helpers/responsive.html
-
    title: Resources
    uri: resources/files.html
    items:
        -
            title: Files
            uri: resources/files.html
        -
            title: Conventions
            uri: resources/conventions.html
        -
            title: Accessilbility
            uri: resources/accessibility.html
