version : 1.0
styleguide:
    title : Prodemos Design System
    brand: Zicht
    outputs: 
        - example
        # - twig
        - html
    assets: 
        -
            type: 'stylesheet'
            path: '../../assets/css/reset.css'
        -
            type: 'stylesheet'
            path: '../../assets/css/main.css'
        -
            type: 'stylesheet'
            path: 'css/prodemos.css'
colors:
    # should be defined in assets/sass/variables/overrides
    white:
    black:
        - black
        - black
        - black-80
        - black-60
        - black-40
        - black-20
    creme:
        - creme-120
        - creme-110
        - creme-80 
        - creme-60 
        - creme-40 
        - creme-20
    yellow:
        - black
        - yellow-110      
        - yellow-80
        - yellow-60
        - yellow-40
        - yellow-20
    orange:
        - black
        - orange-110
        - orange-80 
        - orange-60 
        - orange-40 
        - orange-20 
    red:
        - black
        - red-110
        - red-80
        - red-60
        - red-40
        - red-20
    pink:
        - black
        - pink-110
        - pink-80
        - pink-60
        - pink-40
        - pink-20
    purple:
        - black
        - purple-110
        - purple-80
        - purple-60
        - purple-40
        - purple-20
    blue:
        - black
        - blue-110
        - blue-80 
        - blue-60 
        - blue-40 
        - blue-20   
    green:
        - black
        - green-110
        - green-80
        - green-60
        - green-40
        - green-20
   
scopes:
        pds-s-content : "Content" 

themes:
        pds-t-public : Public
        pds-t-corporate : Corporate
        pds-t-variant01 : Variant01 
        pds-t-variant02 : Variant02 
        pds-t-variant03 : Variant03 
        pds-t-variant04 : Variant04 
        pds-t-variant05 : Variant05 
        pds-t-variant06 : Variant06 

images:
    # will be read from the assets/images/ directory
    # by the build script
    
icons:
    # will be read from the assets/images/icons directory
    # by the build script

