#name: Release
#
#on:
#  push:
#    branches:
#      - master

#jobs:
#  publish:
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 14.17
#      - run: npm install
#      - run: npx semantic-release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
