-
    styleguide_title: Text button, large (=default)
    styleguide_description: Large is the default style of a button if no other properties are given
    styleguide_type: button/text
    text: Button
    url: '#'
    level: primary
    size: large
    bem: false

-
    styleguide_title: Text button, large, accent
    styleguide_description: Accent is always the opposite color of the theme
    styleguide_type: button/text
    text: Button
    url: '#'
    level: primary
    size: large
    accent: true

-
    styleguide_title: Text button, large, disabled
    styleguide_description: A class can be added to disable the button
    styleguide_type: button/text
    text: Button
    url: '#'
    level: primary
    size: large
    disabled: true

-
    styleguide_title: Text button, large, regular icon
    styleguide_description: Icon in front of the text
    styleguide_type: button/icon-prefix
    text: Button
    url: '#'
    level: primary
    size: large
    icon: arrow-circled-left
        

-
    styleguide_title: Text button, large, svg icon
    styleguide_description: Icon behind the text
    styleguide_type: button/icon-suffix
    text: Button
    url: '#'
    level: primary
    size: large
    svgicon:
        name: arrow-right-circle-solid.svg
        width: 22
        height: 22

-
    styleguide_title: Text button, large, with icons
    styleguide_description: Icon both in front of and behind the text
    styleguide_type: button/icon-prefix-suffix
    text: Button
    url: '#'
    level: primary
    size: large
    icon_left: arrow-circled-left
    icon_right: arrow-circled-right
        
-
    styleguide_title: Text button, regular, with 3D-effect
    styleguide_type: button/text
    text: Submit
    url: '#'
    level: primary
    size: regular

-
    styleguide_title: Text button, regular
    styleguide_type: button/text
    text: Submit
    url: '#'
    level: secondary
    size: regular

-
    styleguide_title: Text button, regular, with icon
    styleguide_description: Icon in front of the text
    styleguide_type: button/icon-prefix
    text: Button
    url: '#'
    level: primary
    size: regular
    icon: arrow-circled-left

-
    styleguide_title: Text button, small.
    styleguide_description: Note; a small button can't have the 3D-effect of the 'primary', so it defaults to 'secondary' when given this property
    styleguide_type: button/text
    text: Submit
    url: '#'
    level: secondary
    size: small

-
    styleguide_title: Text button, small, with icon
    styleguide_description: Icon in front of the text
    styleguide_type: button/icon-prefix
    text: Button
    url: '#'
    level: primary
    size: small
    icon: arrow-circled-left

-
    styleguide_title: Text button, small, disabled
    styleguide_type: button/text
    text: Submit
    url: '#'
    level: secondary
    size: small
    disabled: true


-
    styleguide_title: Toggle button
    styleguide_type: button/text
    text: Toggle
    url: '#'
    level: toggle

-
    styleguide_title: Toggle button, disabled
    styleguide_type: button/text
    text: Toggle
    url: '#'
    level: toggle
    disabled: true


-
    styleguide_title: Link button
    styleguide_type: button/text
    text: Button
    url: '#'
    level: transparent

-
    styleguide_title: Link button
    styleguide_type: button/icon-prefix
    text: Button
    url: '#'
    level: transparent
    icon: arrow-right